vim.keymap.set('n', 'gb', '', { desc = 'Buffers' })
vim.keymap.set('n', 'gbn', ':bn<CR>', { desc = 'Go to next buffer' })
vim.keymap.set('n', 'gbp', ':bp<CR>', { desc = 'Go to previous buffer' })
vim.keymap.set('n', ']b', ':bn<CR>', { desc = 'Next buffer' })
vim.keymap.set('n', '[b', ':bp<CR>', { desc = 'Previous buffer' })
vim.keymap.set('n', '<leader>x', function()
  MiniBufremove.wipeout()
end, { desc = 'Close current buffer' })
vim.keymap.set('n', '<leader>X', ':bufdo bw<CR>', { desc = 'Close all buffers' })
